### ISSUE TITLE
Unauthorized response

### ISSUE THREAD

**Issue by remote-pro** [milkywaybrain/cryptogalaxy#4]
Hi Team,
Great initiative going on here.
I'm new to coding & have no background, but have managed to setup the various environments to test, but receive "Unauthorized Access" responses from all exchanges

Example Log (for AAX only):

_{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"logger setup is done"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"mysql connected"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"elastic search connected"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"influxdb connected"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"nats connected"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"clickhouse connected"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"s3 connected"}
{"level":"info","time":"2022-06-10T11:46:28+08:00","message":"terminal connected"}
{"level":"info","exchange":"aax","time":"2022-06-10T11:46:29+08:00","message":"websocket connected"}
{"level":"debug","exchange":"aax","func":"readWs","time":"2022-06-10T11:46:29+08:00","message":"unlike other exchanges aax does not send channel subscribed success message in a proper format"}
{"level":"info","exchange":"aax","time":"2022-06-10T11:46:29+08:00","message":"REST connection setup is done"}
{"level":"error","stack":[{"func":"logErrStack","line":"118","source":"exchange.go"},{"func":"WsTradesToStorage","line":"106","source":"exchange.go"},{"func":"newAAX.func10","line":"179","source":"aax.go"},{"func":"(*Group).Go.func1","line":"75","source":"errgroup.go"},{"func":"goexit","line":"1571","source":"asm_amd64.s"}],"error":"unauthorized: unauthorized access","time":"2022-06-10T11:46:29+08:00"}
{"level":"error","stack":[{"func":"logErrStack","line":"118","source":"exchange.go"},{"func":"WsTradesToStorage","line":"106","source":"exchange.go"},{"func":"newAAX.func14","line":"197","source":"aax.go"},{"func":"(*Group).Go.func1","line":"75","source":"errgroup.go"},{"func":"goexit","line":"1571","source":"asm_amd64.s"}],"error":"code: 241, message: Memory limit (total) exceeded: would use 64.60 TiB (attempt to allocate chunk of 4283259 bytes), maximum: 14.40 GiB","time":"2022-06-10T11:46:29+08:00"}
{"level":"error"**,"error":"unauthorized: unauthorized access",**"exchange":"aax","time":"2022-06-10T11:46:29+08:00","message":"error occurred"}
{"level":"error","time":"2022-06-10T11:46:29+08:00","message":"exiting the app"_}

I'm assuming I now need to add API keys to headers for each of the exchanges, is this the right path to go down?
If so, would you mind providing an example for me to integrate from or suggest an alternate solution please?

**Comment by milkywaybrain** [comment]
Hey, from the log, it seems you got an “unauthorized: unauthorized access” error from one of the storage options you configured.

No need to pass the API key for any of the exchanges as we are accessing only public data through the app.

First try to run the app with only terminal output enabled using the simple config like the following and if it works, then add the required storage option.

```
{
   "exchanges": [
       {
           "name": "aax",
           "markets": [
               {
                   "id": "BTCUSDT",
                   "info": [
                       {
                           "channel": "trade",
                           "connector": "websocket",
                           "websocket_consider_interval_sec": 0,
                           "storages": [
                               "terminal"
                           ]
                       }
                   ],
                   "commit_name": "BTC/USD"
               }
           ],
           "retry": {
               "number": 10,
               "gap_sec": 60,
               "reset_sec": 600
           }
       }
   ],
   "connection": {
       "websocket": {
           "conn_timeout_sec": 10,
           "read_timeout_sec": 0
       },
       "rest": {
           "request_timeout_sec": 10,
           "max_idle_conns": 100,
           "max_idle_conns_per_host": 10
       },
       "terminal": {
           "ticker_commit_buffer": 1,
           "trade_commit_buffer": 1
       }
   },
   "log": {
       "level": "error",
       "file_path": "/var/log/cryptogalaxy/cryptogalaxy.log"
   }
}
```
